name: Deploy to Koyeb

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: "${{ github.ref_name }}"
      cancel-in-progress: true
    steps:
      - name: Install and configure the Koyeb CLI
        uses: koyeb-community/koyeb-actions@v2
        with:
          api_token: "${{ secrets.KOYEB_API_TOKEN }}"

      - name: Build and deploy the application to Koyeb
        uses: koyeb/action-git-deploy@v1
        with:
          app-name: mikiko
          service-name: mikiko
          service-type: worker
          service-env: ENV=prod,BOT_TOKEN=${{ secrets.BOT_TOKEN }},GUILD_ID=${{ secrets.GUILD_ID }}
          service-instance-type: free
          service-regions: fra